### ISSUE TITLE
Ordner Struktur anpassen

### ISSUE THREAD

**Issue by paule96** [Zeroks77/dotNET-Global-Tools#2]
Wir sollten uns an eine allgemeine ordnerstruktur halten. Ca. nach diesem Schema:

src/{Namespace}/    ->   Hier kommt alles das hin was gerade in deinem Ordner Root liegt
test/{Namespace.Test}/   ->   Der Ordner ist optional und wird für Testautomatisierung genutzt
docs/{Namespace}/   ->   Der Ordner ist optional und wird für Dokumentation genutzt wenn diese nicht mehr in die Readme.md passt bzw. wenn du nicht das Wiki von Github verwenden willst.

Des Weiteren wäre es hilfreich für die Benutzer vom Visual Studio noch eine .sln Datei im Root dieses Repos anzulegen. Dies kannst du am besten hiermit machen:

https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-sln

**Comment by Zeroks77** [comment]
Erledigt
