### ISSUE TITLE
Dieses Tool sollte gebaut werden und über einen Feed zum einfachen Download angeboten werden

### ISSUE THREAD

**Issue by paule96** [Zeroks77/dotNET-Global-Tools#4]
Es wäre gut wenn nicht jeder der das Tool benutz unbedingt das Programm erst bauen muss. Dafür gibt es Nuget. Nuget ist eine Packetverwaltung. 

In einem Packet ist dein Code so verpackt das dieser auch von anderen Menschen genutzt werden kann die kein Zugriff auf deinen Sourcecode haben oder diese nicht verstehen wollen. (im Endeffekt alle Nutzer)

Damit du ein Packet packen kannst musst du erst dein Sourcecode kompilieren in etwas das jeder Computer versteht. In der dotnet welt sind das in der Regel .dll und .exe Dateien. Das machst du in der Regel mit ```dotnet build``` Der Output davon hat allerdings den Nachteil das dieser das SDK braucht. Die Nutzer werden in der Regel aber immer nur die Frameworkruntime und eher selten das SDK installiert haben. Somit muss du dein dotnet Programm [publishen](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21). das kannst du am besten mit ```dotnet publish``` machen. 

Hast du dies getan kannst du den Output in ein Nuget Packet verpacken. Danach kannst du dies auf deinem private Feed veröffentlichen. Dazu kannst du dir das [hier](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?toc=%2Fazure%2Fdevops%2Fuser-guide%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fuser-guide%2Fbreadcrumb%2Ftoc.json&view=vsts&tabs=new-nav) schonmal durchlesen.

Deine Build definition kannst mit hilfe von dem [hier](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml) bauen.

Den Rest machen wir dann zusammen. Sonst wird der Issue hier unendlich lang.

**Comment by Zeroks77** [comment]
@paule96 ich denke ich habe das so weit fertig
